model = dict(
    type='Query2LabelClassifier',
    backbone=dict(
        backbone='swin_L_384_22k',
        # backbone = "densenet121-res224-all",
        hidden_dim = 2048, #positional encoding input as well
        position_embedding = "sine",
        num_class = 6,
        img_size = 384,
        pretrained = True,
        fuse_imgs = True),
    neck=dict(
        type='Transformer',
        hidden_dim= 2048,
        img_size = 384,
        position_embedding="sine",
        dropout=0.1,
        nheads=4,
        dim_feedforward=8192,
        enc_layers = 1,
        dec_layers = 2,
        num_class = 6,
        keep_other_self_attn_dec = True,
        keep_first_self_attn_dec = True,
        keep_input_proj = True,
        pre_norm= True),)